// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyTJQkypZbEBFv06KwEieIr4CsccChBs',
    appId: '1:282784319034:web:7bfc6c1c7a4b9daf489703',
    messagingSenderId: '282784319034',
    projectId: 'utsmobile-28e88',
    authDomain: 'utsmobile-28e88.firebaseapp.com',
    storageBucket: 'utsmobile-28e88.firebasestorage.app',
    measurementId: 'G-FCDCTQKBQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaB97SxfvHzB2fc32Sez3bcFb8trKqPAg',
    appId: '1:282784319034:android:6c1421c1c881ede9489703',
    messagingSenderId: '282784319034',
    projectId: 'utsmobile-28e88',
    storageBucket: 'utsmobile-28e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmmeJAnC5TBunzA1eFV2CZPOPwz5e_C4',
    appId: '1:282784319034:ios:d22071b9d82bdff8489703',
    messagingSenderId: '282784319034',
    projectId: 'utsmobile-28e88',
    storageBucket: 'utsmobile-28e88.firebasestorage.app',
    iosBundleId: 'com.example.studentActivityTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPmmeJAnC5TBunzA1eFV2CZPOPwz5e_C4',
    appId: '1:282784319034:ios:d22071b9d82bdff8489703',
    messagingSenderId: '282784319034',
    projectId: 'utsmobile-28e88',
    storageBucket: 'utsmobile-28e88.firebasestorage.app',
    iosBundleId: 'com.example.studentActivityTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtyTJQkypZbEBFv06KwEieIr4CsccChBs',
    appId: '1:282784319034:web:1b2d12e331211e81489703',
    messagingSenderId: '282784319034',
    projectId: 'utsmobile-28e88',
    authDomain: 'utsmobile-28e88.firebaseapp.com',
    storageBucket: 'utsmobile-28e88.firebasestorage.app',
    measurementId: 'G-DEYP8L47DV',
  );
}
